#!/bin/bash
g++ -o ADCMonitor ADCMonitor.cpp bus/SPIDevice.cpp bus/BusDevice.cpp
g++ -o ADCTest ADCTest.cpp bus/SPIDevice.cpp bus/BusDevice.cpp
g++ -o ADCSingle ADCSingle.cpp bus/SPIDevice.cpp bus/BusDevice.cpp